name: bookshell_client
version: 0.0.1
description:
author:
homepage:

dependencies:
    angular2:
    angular2_components:
      git: git://github.com/dart-lang/angular2_components
    browser: ^0.10.0
    dart_to_js_script_rewriter: ^1.0.1
    firebase:
    http:
    cookie:
    

    # sass_transformer: ^0.1.0 ## if you use sass
    # less_dart: ^0.3.4 ## if you use less

dev_dependencies:
    test: ^0.12.13+1
    yaml: ^2.1.9

transformers:
    #- sass_transformer ## if you use sass
    #- less_dart ## if you use less
    - angular2:
        platform_directives:
          - package:angular2/common.dart#COMMON_DIRECTIVES
        platform_pipes:
          - package:angular2/common.dart#COMMON_PIPES
        entry_points: web/mypage/main.dart
    - dart_to_js_script_rewriter
    - $dart2js:
        minify: true
        commandLineOptions:
            - --trust-type-annotations
            - --trust-primitives
