//Auto-generated by RSP Compiler
//Source: list-page.rsp.html
library list_page_rsp;

import 'dart:async';
import 'dart:io';
import 'package:stream/stream.dart';
import 'package:bookshelf_server/user.dart';
import 'package:bookshelf_server/book.dart';
import 'package:bookshelf_server/year.dart';

/** Template, listPage, for rendering the view. */
Future listPage(HttpConnect connect, {List<Book>books,escapedUserID,List<Year>years,int activeYear,int activeMonth,String trackingID}) async { //#4
  HttpResponse response = connect.response;
  if (!Rsp.init(connect, "text/html; charset=utf-8"))
    return null;

  response.write("""<!DOCTYPE html>
<html>
<head>
    <title>"""); //#4

  response.write(Rsp.nnx(escapedUserID)); //#7


  response.write(""" さんのbookshelf</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
    <script>
        (function (i, s, o, g, r, a, m) {
            i['GoogleAnalyticsObject'] = r;
            i[r] = i[r] || function () {
                        (i[r].q = i[r].q || []).push(arguments)
                    }, i[r].l = 1 * new Date();
            a = s.createElement(o),
                    m = s.getElementsByTagName(o)[0];
            a.async = 1;
            a.src = g;
            m.parentNode.insertBefore(a, m)
        })(window, document, 'script', 'https://www.google-analytics.com/analytics.js', 'ga');

        ga('create', 'UA-89660523-1', 'auto');
        ga('send', 'pageview');
    </script>
</head>
<body>
<nav class="navbar navbar-default navbar-static-top">
    <div class="container">
        <ul class="nav navbar-nav">
            <li><a href="/">Top</a></li>
            <li><a href="/mypage">新規登録</a></li>
            <li class="active"><a href="#">読了リスト</a></li>
            <li><a href="/stack/"""); //#7

  response.write(Rsp.nnx(escapedUserID)); //#33


  response.write("""">積読リスト</a></li>
        </ul>
    </div>
</nav>
<div class="container">
    <div class="jumbotron">
        <h1>"""); //#33

  response.write(Rsp.nnx(escapedUserID)); //#39


  response.write(""" さんのbookshelf</h1>
        <p>つながりを作ろう</p>
    </div>

    <div class="calendar">
        <ul class="years nav nav-pills">
"""); //#39

  for (var year in years) { //for#45

    if (year.isActive) { //if#46

      response.write("""                <li role="presentation" class="enable active"><a href="#calendar-"""); //#47

      response.write(Rsp.nnx(year.year)); //#47


      response.write("""">"""); //#47

      response.write(Rsp.nnx(year.year)); //#47


      response.write("""年</a></li>
"""); //#47

    } else if (year.isEnable) { //else#48

      response.write("""                <li role="presentation" class="enable"><a href="#calendar-"""); //#49

      response.write(Rsp.nnx(year.year)); //#49


      response.write("""">"""); //#49

      response.write(Rsp.nnx(year.year)); //#49


      response.write("""年</a></li>
"""); //#49

    } else { //else#50

      response.write("""                <li role="presentation" class="disabled"><a href="javascript:void(0)">"""); //#51

      response.write(Rsp.nnx(year.year)); //#51


      response.write("""年</a></li>
"""); //#51
    } //if
  } //for

  response.write("""        </ul>

        <div class="tab-content">
"""); //#54

  for (var year in years) { //for#57

    response.write("""            <div role="tabpanel" class="tab-pane """); //#58

    response.write(Rsp.nnx(year.isActive ? 'active' : '')); //#58


    response.write("""" id="calendar-"""); //#58

    response.write(Rsp.nnx(year.year)); //#58


    response.write("""">
                <nav aria-label="Page navigation">
                    <ul class="pagination">
"""); //#58

    for (var month in year.months) { //for#61

      if (month.isActive) { //if#62

        response.write("""                                <li class="active"><a href="javascript:void(0)">"""); //#63

        response.write(Rsp.nnx(month.month)); //#63


        response.write("""月</a></li>
"""); //#63

      } else if (month.isEnable) { //else#64

        response.write("""                                <li><a href="/user/"""); //#65

        response.write(Rsp.nnx(escapedUserID)); //#65


        response.write("""/"""); //#65

        response.write(Rsp.nnx(year.year)); //#65


        response.write("""/"""); //#65

        response.write(Rsp.nnx(month.month)); //#65


        response.write("""">"""); //#65

        response.write(Rsp.nnx(month.month)); //#65


        response.write("""月</a></li>
"""); //#65

      } else { //else#66

        response.write("""                                <li class="disabled"><a href="javascript:void(0)">"""); //#67

        response.write(Rsp.nnx(month.month)); //#67


        response.write("""月</a></li>
"""); //#67
      } //if
    } //for

    response.write("""                    </ul>
                </nav>
            </div>
"""); //#70
  } //for

  response.write("""        </div>
    </div>

    <div class="panel panel-default">
        <div class="panel-heading">
            <h2 class="panel-title">読了リスト</h2>
        </div>
            <ul class="list-group">
"""); //#74

  for (var book in books) { //for#82
var title = book.getEscapedTitle();
                var author = book.getEscapedAuthor();
                var date = book.getFormattedDateTime();
                var review = book.review;
                var hasReview = review != null;
                var hasImage = book.image != null && book.asin != null && trackingID != null;

    response.write("""

                <li class="list-group-item">
"""); //#90

    if (hasReview) { //if#92

      response.write("""                    <a href=\""""); //#93

      response.write(Rsp.nnx(review)); //#93


      response.write("""">"""); //#93

      response.write(Rsp.nnx(title)); //#93


      response.write(""" """); //#93

      response.write(Rsp.nnx(author)); //#93


      response.write("""</a>
"""); //#93

      if (hasImage) { //if#94

        response.write("""                            <a href="http://www.amazon.co.jp/gp/product/"""); //#95

        response.write(Rsp.nnx(book.asin)); //#95


        response.write("""?tag="""); //#95

        response.write(Rsp.nnx(trackingID)); //#95


        response.write(""""><img src=\""""); //#95

        response.write(Rsp.nnx(book.image)); //#95


        response.write("""" /></a>
"""); //#95
      } //if

    } else { //else#97

      response.write("""                    """); //#98

      response.write(Rsp.nnx(title)); //#98


      response.write(""" """); //#98

      response.write(Rsp.nnx(author)); //#98


      response.write("""

"""); //#98

      if (hasImage) { //if#99

        response.write("""                            <a href="http://www.amazon.co.jp/gp/product/"""); //#100

        response.write(Rsp.nnx(book.asin)); //#100


        response.write("""?tag="""); //#100

        response.write(Rsp.nnx(trackingID)); //#100


        response.write(""""><img height="100" src=\""""); //#100

        response.write(Rsp.nnx(book.image)); //#100


        response.write("""" /></a>
"""); //#100
      } //if
    } //if

    response.write("""                </li>
"""); //#103
  } //for

  response.write("""            </ul>
    </div>
</div>
<!-- Latest compiled and minified CSS -->
<link
        rel="stylesheet"
        href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"
        integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u"
        crossorigin="anonymous">

<!-- Optional theme -->
<link
        rel="stylesheet"
        href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css"
        integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp"
        crossorigin="anonymous">

<!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>

<!-- Latest compiled and minified JavaScript -->
<script
        src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"
        integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa"
        crossorigin="anonymous"></script>
<script>
    \$('.calendar .years li.enable a').click(function (e) {
        e.preventDefault();
        \$(this).tab('show');
    })
</script>
</body>
</html>"""); //#105

  return null;
}
