//Auto-generated by RSP Compiler
//Source: stack-list-page.rsp.html
library stack_list_page_rsp;

import 'dart:async';
import 'dart:io';
import 'package:stream/stream.dart';
import 'package:bookshelf_server/user.dart';
import 'package:bookshelf_server/book.dart';
import 'package:bookshelf_server/year.dart';

/** Template, stackListPage, for rendering the view. */
Future stackListPage(HttpConnect connect, {List<Book>books,escapedUserID}) async { //#4
  HttpResponse response = connect.response;
  if (!Rsp.init(connect, "text/html; charset=utf-8"))
    return null;

  response.write("""<!DOCTYPE html>
<html>
<head>
    <title>"""); //#4

  response.write(Rsp.nnx(escapedUserID)); //#7


  response.write(""" さんのbookshelf</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
    <script>
        (function (i, s, o, g, r, a, m) {
            i['GoogleAnalyticsObject'] = r;
            i[r] = i[r] || function () {
                        (i[r].q = i[r].q || []).push(arguments)
                    }, i[r].l = 1 * new Date();
            a = s.createElement(o),
                    m = s.getElementsByTagName(o)[0];
            a.async = 1;
            a.src = g;
            m.parentNode.insertBefore(a, m)
        })(window, document, 'script', 'https://www.google-analytics.com/analytics.js', 'ga');

        ga('create', 'UA-89660523-1', 'auto');
        ga('send', 'pageview');
    </script>
</head>
<body>
<nav class="navbar navbar-default navbar-static-top">
    <div class="container">
        <ul class="nav navbar-nav">
            <li><a href="/">Top</a></li>
            <li><a href="/mypage/">MyPage</a></li>
            <li><a href="/user/"""); //#7

  response.write(Rsp.nnx(escapedUserID)); //#32


  response.write("""">読了リスト</a></li>
            <li class="active"><a href="#">積読リスト</a></li>
        </ul>
    </div>
</nav>
<div class="container">
    <div class="jumbotron">
        <h1>"""); //#32

  response.write(Rsp.nnx(escapedUserID)); //#39


  response.write(""" さんのbookshelf</h1>
        <p>つながりを作ろう</p>
    </div>

    <div class="panel panel-default">
        <div class="panel-heading">
            <h2 class="panel-title">読了リスト</h2>
        </div>
            <ul class="list-group">
"""); //#39

  for (var book in books) { //for#48
var id = book.id;
                var title = book.getEscapedTitle();
                var author = book.getEscapedAuthor();

    response.write("""

                <li class="list-group-item">
                    """); //#53

    response.write(Rsp.nnx(title)); //#55


    response.write(""" """); //#55

    response.write(Rsp.nnx(author)); //#55


    response.write("""

                </li>
"""); //#55
  } //for

  response.write("""            </ul>
    </div>
</div>
<!-- Latest compiled and minified CSS -->
<link
        rel="stylesheet"
        href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"
        integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u"
        crossorigin="anonymous">

<!-- Optional theme -->
<link
        rel="stylesheet"
        href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css"
        integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp"
        crossorigin="anonymous">

<!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>

<!-- Latest compiled and minified JavaScript -->
<script
        src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"
        integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa"
        crossorigin="anonymous"></script>
</body>
</html>"""); //#58

  return null;
}
