name: bookshelf_server
version: 1.0.0
description: Hello World Sample Application
dependencies:
  stream: any
  firebase_dart:
  http:
  awsdart:
    git: git://github.com/gjersvik/awsdart.git
  xml:
  archive: